const mongoose = require('mongoose')

const vehicleSchema = new mongoose.Schema({
    media:{
        type:Array,
        required:false
    },
    title:{
        type:String,
        required:false
    },
    description:{
        type:String,
        required:false
    },
    condition:{
        type:String,
        required:false
    },
    country:{
        type:String,
        required:false
    },
    city:{
        type:String,
        required:false
    },
    neighbourhood:{
        type:String,
        required:false
    },
    maker:{
        type:String,
        required:false
    },
    usages:{
        type:String,
        required:false
    },

    final_drive_system:{
        type:String,
        required:false
    },
    wheel:{
        type:Number,
        required:false
    },
    engine_size:{
        type:String,
        required:false
    },
    model:{
        type:String,
        required:false
    },
    build_year:{
        type:String,
        required:false
    },
    dimension:{
        type:String,
        required:false
    },
    boat_engine:{
        type:Boolean,
        required:false
    },
    num_of_engine:{
        type:String,
        required:false
    },
    inboard_outboard:{
        type:String,
        required:false
    },
    kilometer:{
        type:String,
        required:false
    },
    warranty:{
        type:String,
        required:false
    },
    color:{
        type:String,
        required:false
    },
    reginal_specs:{
        type:String,
        required:false
    },
    chassis_num:{
        type:String,
        required:false
    },
    transmission_type:{
        type:String,
        required:false
    },
    vehicle_type:{
        type:String,
        required:false
    },
    doors:{
        type:Number,
        required:false
    },
    body_condition:{
        type:String,
        required:false
    },
    engine_condition:{
        type:String,
        required:false
    },
    capacity_weight:{
        type:String,
        required:false
    },
    engine_type:{
        type:String,
        required:false
    },
    num_of_cylinder:{
        type:String,
        required:false
    },
    fuel_type:{
        type:String,
        required:false
    },
    steering_side:{
        type:String,
        required:false
    },
    seller_type:{
        type:String,
        required:false
    },
    extras:{
        type:Array,
        required:false
    },
    engine_power:{
        type:String,
        required:false
    },
    price:{
        type:Number,
        required:false
    },
    call_for_price:{
        type:Boolean,
        required:false
    },
    quantity:{
        type:Number,
        required:false
    },
    num_plate_city:{
        type:String,
        required:false
    },
    num_plate_type:{
        type:String,
        required:false
    },
    num_plate_Code:{
        type:String,
        required:false
    },
    num_of_digit:{
        type:Number,
        required:false
    },
    plate_design:{
        type:String,
        required:false
    },
    plate_number:{
        type:Number,
        required:false
    },
    spare_part_type:{
        type:String,
        required:false
    },
    part_condition:{
        type:String,
        required:false
    },
    part_seller_type:{
        type:String,
        required:false
    },
    location:{
        type:String,
        required:false
    },
})

module.exports = mongoose.model('Vehicle', vehicleSchema)
